#!/bin/bash
#
# Octree generator start script.
#

# Get script path
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  GSDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$GSDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
GSDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
# Escape spaces in GSDIR
GSDIRESC=$(printf %q "$GSDIR")

LIB_PATH="$GSDIR/lib/*"

#
# Choose java - use JAVA_HOME, if set.
#
if [ "$JAVA_HOME" != "" ]; then
	JAVA="$JAVA_HOME/bin/java"
else
	JAVA="java"
fi

#
# Settings.
#
# Properties file - by default we use the file at $HOME/.gaiasky/global.properties
#OPTS="$OPTS -Dproperties.file=$GSDIRESC/conf/global.properties"

# Memory
OPTS="$OPTS -Xms60g -Xmx160g"

# Parallel GC 
#OPTS="$OPTS -XX:+UseParallelGC"
# CMS GC
OPTS="$OPTS -XX:+UseConcMarkSweepGC"
# G1 GC
#OPTS="$OPTS -XX:+UseG1GC"

# GC debug only
#OPTS="$OPTS -verbose:gc -XX:+PrintGCDetails"
# JIT compiler debug only
#OPTS="$OPTS -XX:+PrintCompilation"
# Even more JIT compiler debugging - This produces a huge XML log file (for JITWatch)
#OPTS="$OPTS -XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:+PrintAssembly"

# Assets location
OPTS="$OPTS -Dassets.location=$GSDIR/"

#
# Run.
#

CMD="$JAVA $OPTS -cp \"$LIB_PATH\" gaia.cu9.ari.gaiaorbit.data.OctreeGroupGeneratorTest $@"
echo "$CMD"

( cd "$GSDIR" && eval $CMD )
