#!/bin/sh
GS_INSTALL_DIR="/opt/gaiasky"
cd "$GS_INSTALL_DIR"

# Link binary
ln -sf "$GS_INSTALL_DIR/gaiasky" /usr/local/bin/

# Move .desktop file
mv "$GS_INSTALL_DIR/gaiasky.desktop" /usr/share/applications/